services:

  backend:
    build: ./backend
    expose:
      - "8000"

  frontend:
    build: ./frontend
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
